---
- name: restart logstash
  become: true
  service:
    name: logstash
    state: restarted
  tags:
  - restart

- name: Restart Filebeat
  become: true
  service:
    name: filebeat
    state: restarted
  tags:
  - restart
