---
# tasks file for converting and moving data_pipeline
- name: Create target folder for holding json document
  file:
    path: "{{common_data_path}}/payload_data/{{item}}/json"
    state: directory
  with_items:
    - lpr
    - rtcc
  tags: create_json_tagets 

- name: Uncompress LRP / RTCC data and prep for move
  shell: 'gunzip {{common_data_pre_copy_loc}}/*.gz'
  run_once: yes
  delegate_to: "{{inventory_hostname}}"
  tags: uncompress_gzs


- name: Copy the Json files to traget at {{common_json_output_target}}
  shell: 'cp -r {{common_data_pre_copy_loc}}/{{file_match}} {{common_json_output_target}}'
  delegate_to: "{{inventory_hostname}}"
  tags: copy_json_to_targets


# - name: List dataset before uncommpress
#   find:
#     path: "{{common_data_pre_copy_loc}}/{{gzip_taget_loc}}"
#     pattern: '*.gz'
#     depth: 3
#   register: "compressed_json_files"
#   tags: list_gzips_by_taget 

# - name: Unarchive a file that is already on the remote machine and move to target location
#   unarchive:
#     src: "{{item}}"
#     dest: "{{common_data_path}}/{{data_type}}/json"
#     remote_src: yes  
#   with_items: "{{ compressed_json_files.path }}"
#   tags: decompress_gzips_by_tagets  

