---
# tasks file for data_move
- name: Copy file from source server to All Logstash nodes
  copy:
    src: "{{common_data_source_dir}}"
    dest: "{{common_destination_target_dir}}" 
    mode: '0644'
    remote_src: true
  become: true
  tags:
  - copy_target_files

- name: Copy Remote-To-Remote (from serverA to serverB)
  synchronize:
    mode: push 
    src: "{{common_data_source_dir}}"
    dest: "{{common_destination_target_dir}}"
    verify_host: true
  delegate_to: "{{common_data_host_server}}" 
  become: true
  tags:   
  - remote_copy_target_files

- name: transfer data from machine1 to machine2 Option 2
  copy: 
    src: "{{common_data_source_dir}}"
    dest: "{{common_destination_target_dir}}"
    remote_src: yes
  delegate_to: "{{target_machine}}" 
  become: true
  tags:   
  - remote_copy_target_files2
