---
- name: restart elasticsearch
  become: true
  service:
    name: elasticsearch
    state: restarted
  tags:
  - restart

- name: reload systemd
  command: systemctl daemon-reload
  become: true
  tags:
  - restart
